### ISSUE TITLE
Client - registering for Valor IT

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#1]
As you scroll down to upload documents we should be able to hover over the requested document (proof of wound, illness or injury) and have a sample of the document. 
![image](https://user-images.githubusercontent.com/46329541/50612148-3941af00-0e96-11e9-80fc-68a5796e27aa.png)

**Comment by pltarr** [comment]
This seems like a _very_ serious issue!

**Comment by pltarr** [comment]
@sa-sturner would you like me to look into this further?

**Comment by sa-sturner** [comment]
@pltarr yes please

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, we would like to have sample documents for all of the Programs that require uploaded docs (such as: Adopt-A-Family, Baby Brigade, Women of Valor, Valor IT). Do you have sample documents that we can link to? If you could post those or send to me via email, that would be great. Thanks!
