### ISSUE TITLE
Admin - Master Settings

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#10]
Logging in as an Admin going into the Master Settings, Job Titles, + Add New Job Title, when trying to do this I receive an error message

![image](https://user-images.githubusercontent.com/46329541/50698181-7e362480-1001-11e9-8336-e61ba120087e.png)

![image](https://user-images.githubusercontent.com/46329541/50698193-85f5c900-1001-11e9-828c-182699e31945.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie -- the "Add New Job Title" bug has been resolved. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr Thank you
