### ISSUE TITLE
Admin: SCT TL settings

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#100]
@putn1nr 
Hi Nicole, 
I set up a profile for our sewing and crafting team leader, under family support.  tadams@soldiersangels.org, pw: heretadams2help.  

With her credentials, she has the ability to change the SA Status for both Angels and service members.  No team leader should be able to change the SA status.

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 

I also noticed that this is the case for deployed support team leader special forces as well.  The permissions allow the team leader to change the SA Status for both Angels and service members.  Team Leaders should not be able to change the SA status for either.  

pfried@soldiersangels.org

here2help

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We had this working (where both Deployed Support Team Leaders and Family Support Team Leaders couldn't update the SA Status). However, it looks like something changed since my last review. We will get this addressed asap. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This has been addressed - Deployed Support and Family Support Team Leaders cannot modify the SA Status. Please let me know if you have any questions. Thanks!
