### ISSUE TITLE
Admin: Special Forces Team Leader

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#101]
@putn1nr 
Hi Nicole, 

The special forces team leader admin status is not able to create a new opportunity under the programs tab.  

pfried@soldiersangels.org

here2help

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Looks like this is the only Program where the Team Leader cannot see the "Add New Opportunity" button. We will get this addressed. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This has been completed as well. Please let me know if you have any questions. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
Thank you for all of the work you and your team are doing!
