### ISSUE TITLE
Admin: Special Forces - error message

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#102]
@putn1nr 
Hi Nicole, 
While working in the special forces team leader admin log in, in the programs tab, pending, pulled up Johnny Good, set to approved clicked save and the error popped up. 
![image](https://user-images.githubusercontent.com/46329541/55418522-17f16d00-5530-11e9-8d95-daa0f878a6c9.png)

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
Is it possible that the service members are being duplicated?  Johnny has 2 profiles.

**Comment by sa-sturner** [comment]
@putn1nr 
Nicole, this is also under the special forces admin under programs tab and possible duplications. 

![image](https://user-images.githubusercontent.com/46329541/55419821-d7dfb980-5532-11e9-88dd-bdb335b584ac.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We will take a look into this - this has been documented and sent to the team. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This has been taken care of. Please let me know if you have any observations. Thanks!
