### ISSUE TITLE
Admin: Special Forces - Angel Placement

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#103]
@putn1nr 
Hi Nicole, 
For the special forces admin the team leader needs to be able to approve angel placement.  This is the note from the programs and rules document.  

Team   Angel requests an opportunity placement. That goes into cue and the team leader will manually assign those opportunities out to Angels.
--

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. My apologies for not understanding - are Special Ops Opportunities not supposed to show up when doing a search in the Team Angel Portal? These Opportunities are only assigned manually via the Special Ops Team Leader? Please advise. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

The angels can "request" to participate in an opportunity but then the team leader makes the final placement.
