### ISSUE TITLE
PRIORITY! Admin - Cards Plus

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#105]
@putn1nr 
Hi Nicole, 

The cards plus team leader permissions, jmott@soldiersangels.org does not have any information under the Programs - Pending requests it is blank.  

Both the team leader and the admin permissions there is nothing listed under the Angels tab.  

Also the Cards Plus programs does not have the Activity Tab. Why? 

When submitting a cards request the zip code only allows five digits it does not allow for +four, this needs to be across the board for all zips.  - please ask if you do not understand.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Please see my notes below for your points regarding the Cards Plus Program:

The cards plus team leader permissions, jmott@soldiersangels.org does not have any information under the Programs - Pending requests it is blank. **NP: This will be addressed. We will also get the "Create New Card Request" button to display as well.**

Both the team leader and the admin permissions there is nothing listed under the Angels tab. **NP: I am not seeing this issue. When logging in as my Deployed Support Team Leader, I see 2 pages worth of "Angels". See the screenshot below:**

![image](https://user-images.githubusercontent.com/46578151/55832587-df2f3600-5ae3-11e9-913b-ce1180afc397.png)

**Could you provide me with the password for the jmott@soldiersangels.org account?**

Also the Cards Plus programs does not have the Activity Tab. Why? **NP: This has been scoped and the team is working on getting the "Activity" tab for the Cards Plus Program.**

When submitting a cards request the zip code only allows five digits it does not allow for +four, this needs to be across the board for all zips. **NP: Would you like us to have a separate, non-required Zip +4 field (to the right of all of the "Zip Code" fields throughout the system)? Here is a screenshot example:**

![image](https://user-images.githubusercontent.com/46578151/55832940-a2b00a00-5ae4-11e9-9a6d-762ed02ffba2.png)

Thanks!
Nicole

**Comment by sa-sturner** [comment]
@putn1nr 

Hi Nicole, I am so sorry for my delay.  The password is:  want2help

I think the suggestion that you provided for the zip+4 is great.  We just can't have the +4 a required field.  I also wonder though if Zip listed twice would be confusing.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Wanted to provdie an update here: 

- When logging into the jmott@soldiersangels.org account, the Pending Requests and Angels List Views are now populated with results.

- The "Create New Card Request" button is displaying when logged in as an Admin, Team Leader, etc.

- The "Activity" tab has been added and can be viewed.

- I have created a new task for adding in the "Zip +4" (non-required field) to the forms. As this has not been completed yet.

Please let me know if you have any observations. Thanks!
