### ISSUE TITLE
Admin: deployed support

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#108]
@putn1nr 

When approving deployed adoptions the system automatically places them on Angel Bakers.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will have this addressed. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr Great!  Thank you Nicole

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Just wanted to let you know that this has been addressed. Please go ahead and review and let me know if you have any questions. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Great Nicole!  we will get it tested.  

Thanks
