### ISSUE TITLE
Registration - Team Angel date of birth

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#11]
While registering as a new team angel it allowed me to put a date in the future for my date of birth. 

![image](https://user-images.githubusercontent.com/46329541/50698822-4b8d2b80-1003-11e9-9ef4-f11da65e5a1f.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, happy Friday! The "Birthdate" field on the Angel/Team Angel form has been addressed. Let me know if you have any questions, thanks!

**Comment by sa-sturner** [comment]
@putn1nr  Happy Friday Nicole!  Great, we will check it out.
