### ISSUE TITLE
Admin:  Deployed Support Team pfried@soldiersangels.org

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#110]
@putn1nr 
Hi Nicole, 

When Pat Fried uses her admin login, pfried@soldiersangels.org pw here2help. Under her programs tab when she clicks on + Create New Opportunity does not work.  When she clicks it nothing happens.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! When I logged into Pat Fried's account, I was not able to replicate the "Add New Opportunity" button not working. However, I did notice an issue when I clicked into the "Add New Opportunity" modal popup, closed out, and then opened it again. We will have the issue I discovered corrected and then maybe Pat can try logging in again/testing again. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr Thanks Nicole, we will test it out.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Sounds good - please let me know if you're still experiencing an issue. The issue that I found (as mentioned above) has already been addressed. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thanks Nicole, should be all set.
