### ISSUE TITLE
Registration: Team Angel donation

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#111]
@putn1nr 
Hi Nicole, we will need to have Team Angels be able to register even if they do not complete the donation.  We have some Team Angels that pay by check or PayPal, for these Team Angels I manually approve them in the admin section.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. You got it. We will make sure that payment via cash, check, PayPal, etc. is considered when doing the Blackbaud integration. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
 Thanks Nicole.

**Comment by sa-sturner** [comment]
On task list.
