### ISSUE TITLE
Admin & Angel log ins:  no comments 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#112]
@putn1nr 
Hi Nicole, 
In the original wireframes, we are able to see the message to the angel when searching for cards plus opportunities.  But you are no longer able to view comments or anything when searching.  This is needed for the angels to be able to view the comments.  

It is the same for the Admin when approving cards plus opportunities, we are not able to see the comments anywhere.  

![image](https://user-images.githubusercontent.com/46329541/58485722-cd503380-8121-11e9-86e8-918e6b814087.png)

**Comment by putn1nr** [comment]
@sa-sturner Hey Susie. Got your note. This has been scoped and will be addressed. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thanks Nicole

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This was done (my apologies for not updating!).
