### ISSUE TITLE
Admin: Sort feature 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#113]
@putn1nr 
Hi Nicole, 
During a call earlier this year it was discussed that we would be able to click on a column header and be able to sort by that header.  Is this being worked on?  

![image](https://user-images.githubusercontent.com/46329541/58486861-e6f27a80-8123-11e9-974d-61fe868a540b.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This is underway. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, sounds great!  Thank you

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This was done (my apologies for not updating!).
