### ISSUE TITLE
Angel: Registered male - WOV

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#114]
We registered a new angel that was male and he was able to join WOV.  WOV and LOL are female only angels per original program rules.

**Comment by putn1nr** [comment]
@sa-sturner Hey Susie. This will be addressed. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, thank you

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, this was completed but never closed out. My apologies!

**Comment by sa-sturner** [comment]
Great!
