### ISSUE TITLE
Angel Profile- LWT and LOL additional questions

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#115]
@putn1nr 
Hi Nicole, 
If possible we would like the order of the number of sm requested to be in the same order.  

Currently, Letter Writing is:  one, two, three 

and  Ladies of Liberty is:  three, two, one 

We would like both to be one, two three.  

![SM request 2](https://user-images.githubusercontent.com/46329541/60280890-13371d80-98c1-11e9-9a1d-eb8f8c83fad3.JPG)
![SM request question](https://user-images.githubusercontent.com/46329541/60280891-13371d80-98c1-11e9-926b-82b67d136226.JPG)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will have this addressed. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank you Nicole

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This is completed.
