### ISSUE TITLE
Card vs. Cards

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#119]
@putn1nr 
Hi Nicole, 

This should be Cards not Card throughout the system. 

![image](https://user-images.githubusercontent.com/46329541/64463984-597bda80-d0c3-11e9-94ca-6179997b69ba.png)

**Comment by putn1nr** [comment]
@sa-sturner Hey Susie! This has been corrected every where except on the Program List View (we will have it corrected).

Just for future reference, if you update the Program Name (in the Program > Program Settings section), it will update the Program Name throughout the entire application.

![image](https://user-images.githubusercontent.com/46578151/64723607-d67dca00-d49e-11e9-95b0-4529e5f718b3.png)

Thanks!
Nicole

**Comment by sa-sturner** [comment]
That is great to know, thank you Nicole.

**Comment by sa-sturner** [comment]
Completed, thank you
