### ISSUE TITLE
Registration - Angel or Team Angel how did you hear

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#12]
When using the drop-down menu and selecting a friend, there is not an ability to type in a name

![image](https://user-images.githubusercontent.com/46329541/50699183-598f7c00-1004-11e9-9c5c-3cde1ca8166a.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This task has been completed on the Angel/Team Angel Signup. Please review and let me know if you have any questions or additional feedback. Thanks!
