### ISSUE TITLE
PRIORITY:  ADMIN:  Angel Documents

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#121]
@putn1nr 
Hi Nicole, 

While training I was not able to upload any documents into an Angel profile.  It allowed me to select a document to upload but I was not able to actually upload it. 

Susie

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Do you mind sending me the file that you are trying to attach to the Angel profile (also send me the name of the Angel as well, please)? I am wondering if maybe this has something to do with the file size. 

Thanks,
Nicole

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole,  Here is our list for angel attachments
Volunteer application
Receipt of the volunteer handbook
Consent to background check
Completed background check
Interview 
Signed position description
VAVS Representative certification
VAVS Deputy certification
VA appointment letter
VAVS Representative de-certification letter
VAVS Deputy de-certification letter
Misc.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Thank you for this! Could you pass along the file that you were attempting to upload yesterday (that was giving you an error)?

Thanks,
Nicole

**Comment by sa-sturner** [comment]
@putn1nr Hi Nicole, it was a couple of different files, I'm sorry I don't remember which ones specifically cause I kept trying different ones.  I know I tried a PDF and a Word document.

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
I know that the data is still priority but I wanted to update you on the ability to upload documents into an Angel profile.  I tried a picture and a PDF and nothing uploaded.  I was testing out the following Angel profile:  James Gilliland.

![2c38bbd561fd1c3444c5c96fdf36f0b8](https://user-images.githubusercontent.com/46329541/65048247-09054800-d921-11e9-8b7c-0d31cd5c6bda.jpg)
[Deployed Support Card Request.pdf](https://github.com/pltarr/sa-database-testing/files/3621699/Deployed.Support.Card.Request.pdf)

**Comment by sa-sturner** [comment]
@putn1nr 
I just looked back at James profile and the PDF, is in there now.
