### ISSUE TITLE
Registration - Team Angel selecting a team

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#13]
When selecting a team to be a part of the "?" is the same thing listed below, not sure both are needed. 

![image](https://user-images.githubusercontent.com/46329541/50699254-99566380-1004-11e9-8a3e-a85067acef29.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, couple thoughts here. We can limit the character count of the Program Description on the Signup (say, 150 characters for example). And if the user "hovers" over the question mark icon, they can get the full description. Or, we can remove the question mark icon all together and just display the entire Program Description. What are your thoughts?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We made the update on the Angel/Team Angel and Service Member Sign Up forms where we are now only showing 150 characters of the Program Description. If you click on the question mark icon, the rest of the description appears. 

Please let me know if you have any questions. Thanks!
