### ISSUE TITLE
Registration - Team Angel when complete

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#14]
Once you submit the registration it just says thank you, does not take you to a login page the website or anywhere.  

![image](https://user-images.githubusercontent.com/46329541/50699333-cc98f280-1004-11e9-8438-cb8a3de5d827.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We have modified the "Thank You" pages for both the Angel/Team Angel Signup form as well as the Service Member Signup form. The verbiage is now:

Thank you for signing up for Soldiers' Angels. A Soldiers' Angels Administrator has received your request.

Please check your email to verify your email address.

[Button linking to the Angel/Team Angel Login or the Service Member Login]

If you'd like us to change this text, please just provide what it is you'd like to state on the "Thank You" pages and we can update. Thanks!
