### ISSUE TITLE
Admin - Team Angel individual team status

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#15]
The drop down list for the individual team status does not match the rules spreadsheet.  

![image](https://user-images.githubusercontent.com/46329541/50699633-a3c52d00-1005-11e9-8cd0-01e22ae8eff8.png)

Status   Categories of Team Angels - BLANK:  Team Angel is not on   any team;  ACTIVE:  Team Angel is on one or   more teams; REQUESTED:  For the teams that require more vetting,   Team Angels may request to join that team ; HOLD:  Team Angels may request   to be placed on hold for 30 or 60 days (may request from their dashboard) for   personal reasons;  INACTIVE: A Team Leader may place a   Team Angel on inactive status,  but   must provide a reason why placed on inactive;    SUSPENDED -   volunteer that has requested to be removed from Soldiers' Angels and   discontinued donation; BARRED - someone that Soldiers' Angels does not want to work with.
--

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The "SA Status" and "Program Status" options for Team Angels have been addressed on the application.

Please review and let me know if you have any questions. Thanks!
