### ISSUE TITLE
Admin - Team Angel status

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#16]
The Team Angel status does not match the spreadsheet. 

![image](https://user-images.githubusercontent.com/46329541/50700466-dcfe9c80-1007-11e9-870c-6447e99060e7.png)

Status   Categories for Volunteers:  ANGELS - any volunteer not   participating on the teams (mostly VA program); TEAM   ANGELS - verified volunteers that pay an annual   gift, participate on the teams and can also participate like an Angel; HOLD - any volunteer on hold   (reasons vary) still paying monthly donation; SUSPENDED - volunteer that has requested to be removed from Soldiers'   Angels and discontinued donation; BARRED - someone that Soldiers' Angels does not want to work with.
--

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The "SA Status" for Angels/Team Angels have been updated. 

Please let me know if you have any questions. Thanks!
