### ISSUE TITLE
Client - deployed registration

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#18]
Would it be possible to change the wording on deployed?  
![image](https://user-images.githubusercontent.com/46329541/51137900-f8825800-17fc-11e9-9ef3-d17109570a25.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We can absolutely change the reference to "Deployed" on the Service Member Signup. What would you like to change it to? Just let me know!

**Comment by tlcurran** [comment]
Active Duty, Active Duty Deployed, Wounded/Injured

If a bubble is available, having something about Active Duty having to be in combat or humanitarian area, may be useful.

**Comment by sa-sturner** [comment]
> Active Duty, Active Duty Deployed, Wounded/Injured
> 
> If a bubble is available, having something about Active Duty having to be in combat or humanitarian area, may be useful.

@tlcurran  would you want the Active Duty Deployed to have the bubble having to be in combat or humanitarian area? 

What would you want a bubble for Active Duty to be? 

And then maybe for Wounded/Ill/Injured the bubble could be Must be post 9/11?

**Comment by sa-sturner** [comment]
@putn1nr 

I think the bubble might be the best way to go. 

leave the drop down as Active Duty, Deployed, Wounded/Ill/Injured

Bubble: 

Active Duty
Deployed - Active Duty deployed to a combat or humanitarian area
Wounded/Ill/Injured - a Post 9-11 wounded, ill and injured veteran

**Comment by putn1nr** [comment]
@sa-sturner Hey Susie. I got it, we will get the text added. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thanks Nicole :)  Happy Monday

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We got the bubble/help text added to the "Qualifying Person's Status" field on the Service Member Signup form. However, I see that there is no text to describe "Active Duty". Can you please provide that so we can update. Here's a screenshot:

![image](https://user-images.githubusercontent.com/46578151/54716077-58fa8200-4b2b-11e9-866c-d28d48c52c5a.png)

Thanks!
