### ISSUE TITLE
Client - Registration for deployed service member post dating

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#19]
Using email address sturner2@soldiersangels.org signing up as a female moving the system allowed me to put a mail stop date in the past.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, happy Friday! The "Mail Stop Date" field on the Service Member form has been addressed. The Service Member can no longer enter a date in the past. Let me know if you have any questions, thanks!

**Comment by sa-sturner** [comment]
@putn1nr Great!  Thank you
