### ISSUE TITLE
Client - registration confirmation email

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#2]

**Comment by sa-sturner** [comment]
Will the confirmation email once registered have more information? Is this editable?  Or is it just to confirm the email address. 

![image](https://user-images.githubusercontent.com/46329541/50613138-d2be9000-0e99-11e9-87bc-11c26e95c36b.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, the "authorization" email is a non-editable email at this time (i.e. you do not have the ability to edit email communication text from the Soldiers' Angels application). However, I'd be happy to scope any text changes you'd like to make to the email. 

The notion behind this email is to have the Service Member "authenticate" his/her account before being able to login to the Service Member Portal. This confirms that he/she is a real person/user of the system.

**Comment by sa-sturner** [comment]
@putn1nr so is this the only email confirmation that they will receive?  Nothing saying thank  you for registering your user id is .....  or pleaser contact ..... should you have any questions.

**Comment by sa-sturner** [comment]
@putn1nr I don't think this will work for the clients after talking through it with our team we are not sure that they will go this extra step.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The Service Member and Angel/Team Angel authorization emails have been disabled at this time (primarily for testing). If/when you want us to turn them back on, just let me know.

**Comment by sa-sturner** [comment]
@putn1nr 
we will be able to set up an automated email to go out after someone registers, correct?  Like a Welcome to Soldiers' Angels thank you for joining (Team Angel email).

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Currently, in the Soldiers' Angels Admin, there is no way to add, edit, or delete email communications that go out of the system. These are hard coded.

However, if you have ideas for the text for the Team Angel Welcome/Confirmation email communication, we can rework the text at any time. Just send me what you like us to change, and I'd be happy to scope it.

Below is a screenshot of the current Confirmation email that the Team Angels will receive:

![image](https://user-images.githubusercontent.com/46578151/52967698-dab68e80-3378-11e9-9f94-bc4fdaa95553.png)

Thanks,
Nicole

**Comment by sa-sturner** [comment]
@putn1nr 
But as part of the automation will Angels and Clients be receiving a welcome email?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Yes, the Welcome/Confirmation email will definitely be auto generated upon signup. And we can have one unique to both Team Angels and Service Members.
