### ISSUE TITLE
Client - Registering as a deployed service member, special forces

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#20]
When registering as a deployed service member checking special forces they are not able to participate in Angel Bakers, Letter Writing, Deployed Adoptions, Ladies of Liberty, Chaplain Support or Troop Birthday (they do not participate in these if they are special forces). But they should be placed in Special Forces, this was not done. 

![image](https://user-images.githubusercontent.com/46329541/51139666-bdceee80-1801-11e9-8ae1-aef85686ce18.png)

There were no additional questions for Special Forces. 
![image](https://user-images.githubusercontent.com/46329541/51141632-09d06200-1807-11e9-98d8-d7e41c5bd68c.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will make this adjustment, not a problem. Do Special Ops Service Members get - Adopt-A-Family or Baby Brigade Programs? or JUST the Special Ops Program?

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole,
Yes, Special Forces can get Adopt-A-Family and Baby Brigade
