### ISSUE TITLE
Client - registering as a deployed service member, chaplain

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#21]
Registering as a deployed service member and checking off that I am a chaplain
![image](https://user-images.githubusercontent.com/46329541/51142438-38e7d300-1809-11e9-9f79-2b4386fcd163.png)

It did not place me on the chaplain support team in step 2
![image](https://user-images.githubusercontent.com/46329541/51142379-08079e00-1809-11e9-8c82-37a80ddcc044.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This item has been completed. On Step 1, when selecting "Chaplain", on Step 2, the "Chaplain Support" program is selected by default and the Service Member does not have the ability to de-select.

Please let me know if you have any questions. Thanks!
