### ISSUE TITLE
Client - registering as deployed opting into baby brigade

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#22]
Signing up as a male deployed service member opting into baby brigade on step 2.  When I get to step 3 to complete the baby brigade questions there is no place for me to put in the spouse/significant others information.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We have added the Spouse/Significant Other fields when filling out the questions for the Baby Brigade Program. See the screenshot below:

![image](https://user-images.githubusercontent.com/46578151/54715954-01f4ad00-4b2b-11e9-868a-82660d91a0e4.png)

Please review and let me know if you have any questions. Thanks!
