### ISSUE TITLE
Client - Deployed Registration Country

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#25]
IS THIS COUNTRY SERVING IN OR COUNTRY FROM.  IF COUNTRY SERVING FROM, CAN WE ONLY LIST THOSE QUALIFIED, IF COUNTRY FROM, IT SHOULD ONLY BE USA OR USA TERRITORIES.

[CLIENT - REGISTRATION COUNTRY.pdf](https://github.com/pltarr/sa-database-testing/files/2803856/CLIENT.-.REGISTRATION.COUNTRY.pdf)

**Comment by sa-sturner** [comment]
@putn1nr 

Can we just remove the Country question from the Service Members registration?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Somehow I missed this. We can absolutely remove the "Country" question from the Service Member Signup. Is that how you would like to proceed with this task? Please advise. Thanks!
