### ISSUE TITLE
Client - Deployed Registration phone number

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#27]
There is possibility of international phone numbers being entered.  How can this be handled?

[Client - Deployed Phone number.pdf](https://github.com/pltarr/sa-database-testing/files/2803877/Client.-.Deployed.Phone.number.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! I would suggest that on the "Phone Number" field we have a bubble where we include instruction that this is a stateside/home phone only and that we do not need a deployed phone number. Do you have any suggestions for the text we should add to the bubble?

**Comment by tlcurran** [comment]
I would think "Stateside phone number only" would work.

**Comment by putn1nr** [comment]
@tlcurran Thanks, Tracy! We will get the text added.

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
You have this one listed as being assigned to me.  What else is needed?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, happy Friday! This one is actually already in progress and I must not have re-assigned myself to this. Sorry about that.

**Comment by sa-sturner** [comment]
@putn1nr 
Happy Friday Nicole!  That is perfect.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This one is completed. Please go ahead and check. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank You Nicole
