### ISSUE TITLE
Client - Deployed Registration - Home State

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#29]
Can this be defined to state "Home of Record" or "Duty Station State" or maybe an added field so it says "Home of Record" for one field and "Duty Station State" for other.

[Client - Home State.pdf](https://github.com/pltarr/sa-database-testing/files/2803902/Client.-.Home.State.pdf)

**Comment by sa-sturner** [comment]
@putn1nr: would it be possible on the deployed sign up to have two Home States?

**Comment by tlcurran** [comment]
Service members or those registering never know what to put in this field.  They will enter the state in which they are currently calling home or their home of record from when they joined.

**Comment by sa-sturner** [comment]
@putn1nr  for those registering as active and/or deployed can we have an explanation for Home State or a bubble saying that this is their Duty Station State?

**Comment by sa-sturner** [comment]
Please include a bubble for Home State:  Duty station for Deployed and Active Duty; State of current residence for Wounded/Ill/Injured 

![image](https://user-images.githubusercontent.com/46329541/52575415-665d7780-2ddb-11e9-806f-e82ac118d9a8.png)

**Comment by putn1nr** [comment]
@sa-sturner / @tlcurran Hi ladies! We can absolutely add the bubble text to the "Home State" field on the Service Member signup. It's been scoped and sent to the team. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner / @tlcurran Hi Susie & Tracy. This has been completed, please check. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank you Nicole
