### ISSUE TITLE
Team Angel - Registering volunteer agreement

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#3]
There is not a link to open the volunteer agreement.

![image](https://user-images.githubusercontent.com/46329541/50615108-6b580e80-0ea0-11e9-9054-15378de629cf.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, any chance that you can send us the Angel/Team Angel Volunteer Service Agreement? Once we get this we can link to it, not a problem. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr I will get you a copy of the agreement.  Thank you

**Comment by putn1nr** [comment]
@sa-sturner Thank you, Susie!

**Comment by sa-sturner** [comment]
@putn1nr would it be possible to have a volunteer agreement for Angels and then a separate one for Team Angels?  or is there one for either volunteer?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie, we can have separate Volunteer Agreements for Angels and Team Angels. The form changes based on the Angel/Team Angel designation so this shouldn't be a problem. Thanks!
