### ISSUE TITLE
Client - Deployed Registration - Baby Brigade

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#30]
Baby Brigade needs to be clear of requirements for when you can register for this support and when your child is too old, as to not waste the TL's time.

[Client - BB registration deployed.pdf](https://github.com/pltarr/sa-database-testing/files/2803940/Client.-.BB.registration.deployed.pdf)

**Comment by sa-sturner** [comment]
@putn1nr 
Nicole, 
This is something we can do via the Program Description as an Admin.
