### ISSUE TITLE
Client - Deployed Registration - AAF # of family members

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#31]
Family size should always be at least 1 more than number of children.

[Client - Deployed Registration - AAF # family members.pdf](https://github.com/pltarr/sa-database-testing/files/2803978/Client.-.Deployed.Registration.-.AAF.family.members.pdf)

**Comment by tlcurran** [comment]
Should not allow over 18 years of age.

[Client - Deployed Registration - AAF age of children.pdf](https://github.com/pltarr/sa-database-testing/files/2803995/Client.-.Deployed.Registration.-.AAF.age.of.children.pdf)

**Comment by tlcurran** [comment]
I typed 4 into both spots.  This was an issue I noticed in  Samaritian this year.  Families would list their kids only in both fields and we want to collect parent/guardian info in the "family size".

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
On your spreadsheet you have this assigned to me is there something you need from me?  

On this portion (below), we did have a suggested solution (we thought it was assigned to me) could we have a drop down of ages? Less than 1, 1, 2, 3, etc. up to 17? 
> Should not allow over 18 years of age.
> 
> [Client - Deployed Registration - AAF age of children.pdf](https://github.com/pltarr/sa-database-testing/files/2803995/Client.-.Deployed.Registration.-.AAF.age.of.children.pdf)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Another one it looks like I missed (my apologies!). We can add a dropdown for "Age" on the Adopt-A-Family Program questions. Is this something you'd like us to proceed with? I will get this one scoped and into the queue. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
We can leave this for Phase 2
