### ISSUE TITLE
Client - Deployed Registration AAF Christmas Wish List

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#32]
Can this be in a list format and a bubble that reminds those registering that cost has to be between $30-50 per listed item.

[Client - Deployed Registration - AAF Wish List.pdf](https://github.com/pltarr/sa-database-testing/files/2804017/Client.-.Deployed.Registration.-.AAF.Wish.List.pdf)

**Comment by sa-sturner** [comment]
Very Similar to #33, 
We would like to add a ? bubble to explain why the message to the angel is so important.  (we will get you the exact wording. **This can be done in phase 2, if we are able to get it completed by August 1, 2019.**

**Comment by putn1nr** [comment]
@sa-sturner / @tlcurran Hi Susie & Tracy. We added the bubble/help text on the Adopt-A-Family "Christmas Wish" field. Also broke out the 1 large field into 5 indivdidual fields (with the ability to add more). 

We can most certainly get bubble/help text added to any of the other fields on the Adopt-A-Family form. Shouldn't be a problem getting it done by 8/1/19! We can create a brand new GitHub task once you have the copy perfected.

Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thanks Nicole
