### ISSUE TITLE
Client - Deployed Registration - AAF Explain why need assistance

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#33]
Can this be in a list format and a bubble that reminds those registering that cost has to be between $30-50 per listed item.

**Comment by tlcurran** [comment]
Did not share with Nicole.  Am I being too nit picky?

**Comment by sa-sturner** [comment]
@tlcurran we should be able to do bubbles yes, with the cost range.  Also a sample of the message to angel.

**Comment by sa-sturner** [comment]
@tlcurran @putn1nr 
Same as #32  this one can be closed

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
This is a different issue from #32 
We would like to add a ? bubble to remind families that the cost range is $30 - $50 (we will get you the exact wording.  **This can be done in phase 2, if we are able to get it completed by August 1, 2019.**

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Based on the note on #34 you mention this is a Phase 2 task.

Just want to clarify though. What bubble/help text are we adding to the "Explain why you need assistance" field? Please advise.

Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Phase2 is great
