### ISSUE TITLE
Client - Deployed Registration - AAF Message to Adopting Angel

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#34]
Maybe a pop out with either examples or a blurb about why it is important to write this message.

[Client - Deployed Registration - AAF message to adopting.pdf](https://github.com/pltarr/sa-database-testing/files/2804032/Client.-.Deployed.Registration.-.AAF.message.to.adopting.pdf)

**Comment by tlcurran** [comment]
Did not share with Nicole yet, not sure again if I'm being too nit picky.

**Comment by tlcurran** [comment]
Team questions during registration.  Can these be open and not plus sign

[Client - Deployed Registration - Team Questions.pdf](https://github.com/pltarr/sa-database-testing/files/2804211/Client.-.Deployed.Registration.-.Team.Questions.pdf)

**Comment by sa-sturner** [comment]
@tlcurran I think it looks cleaner with the +

**Comment by tlcurran** [comment]
I get that completely and agree, but service members are going to skip them and hit submit.  Does it allow them to skip?  I'll try to test today.

**Comment by sa-sturner** [comment]
What if we asked that they are required fields?

**Comment by tlcurran** [comment]
That would be the PM or VP decision, but I think it would be a good thing.

**Comment by sa-sturner** [comment]
> Team questions during registration. Can these be open and not plus sign
> 
> [Client - Deployed Registration - Team Questions.pdf](https://github.com/pltarr/sa-database-testing/files/2804211/Client.-.Deployed.Registration.-.Team.Questions.pdf)

@putn1nr 
Hi Nicole, 

We would like to make these Mandatory fields, but leave them closed - make all the questions required.

**Comment by sa-sturner** [comment]
> Maybe a pop out with either examples or a blurb about why it is important to write this message.
> 
> [Client - Deployed Registration - AAF message to adopting.pdf](https://github.com/pltarr/sa-database-testing/files/2804032/Client.-.Deployed.Registration.-.AAF.message.to.adopting.pdf)

@putn1nr 
Hi Nicole, on this one we will hold off on phase 2 if can be completed by Aug 1 2019, the same as #33

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Same thing here. Just want to clarify:

- Phase 2 task
- What bubble/help text do you want on the "Message to adopting angel" field.

Thanks!

**Comment by putn1nr** [comment]
@sa-sturner One other question: want all Program questions to be required? For all Programs?

**Comment by sa-sturner** [comment]
@putn1nr 
Phase 2 is great
