### ISSUE TITLE
Client - Deployed Registration - Baby Brigade DOB of child

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#35]
Date should only allow to go back 364 days or ahead ( I believe) six months but Melissa will have to confirm

[Client - Deployed Registration - Baby Brigade DOB.pdf](https://github.com/pltarr/sa-database-testing/files/2804229/Client.-.Deployed.Registration.-.Baby.Brigade.DOB.pdf)

**Comment by sa-sturner** [comment]
Six months is too far out, family eligibility is 3 months prior to the birth.

**Comment by tlcurran** [comment]
Also let me register for a child not pregnant with yet.  More than 12 mo out.

[Client - Deployed Registration - Baby Bridgade DOB.pdf](https://github.com/pltarr/sa-database-testing/files/2804392/Client.-.Deployed.Registration.-.Baby.Bridgade.DOB.pdf)

**Comment by tlcurran** [comment]
Thanks Susie.  Can we get the dates set so it won't allow this and give them a message as to why?

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 

This is from the rules of the program that was submitted:  A families eligibility is 90 days prior to the due date but no later than 364 days of birth.  I
