### ISSUE TITLE
Client - Deployed Registration - Baby Brigade Question - Dad

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#36]
For deployed, there must be a deployment address, so maybe a bubble here for Deployed or change "City" to City/APO/FPO/DPO and for "State" to State/AP/AE/AA.

[Client - Deployed Registration - BB Dad address.pdf](https://github.com/pltarr/sa-database-testing/files/2804262/Client.-.Deployed.Registration.-.BB.Dad.address.pdf)

**Comment by putn1nr** [comment]
@tlcurran / @sa-sturner Hi ladies! What would you prefer here? A bubble by the "City" and "State" fields. Or woudl you rather the titles be changed from: "City" to = "City/APO/FPO/DPO" and "State" to = "State/AP/AE/AA"?

Please advise. Thanks!

**Comment by tlcurran** [comment]
The latter of the two would be my preference.

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! We modified the "City" and "State" field names to include: "City/APO/FPO/DPO" and "State/AP/AE/AA". Please go ahead and check. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank you, Nicole
