### ISSUE TITLE
Client - Deployed Registration - DAT Question

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#37]
DAT question "Message to adopting Angel" needs a bubble with statement about why it's important to leave a message and some examples

[Client - Deployment Registration - DAT Questions.pdf](https://github.com/pltarr/sa-database-testing/files/2804278/Client.-.Deployment.Registration.-.DAT.Questions.pdf)

**Comment by sa-sturner** [comment]
@tlcurran can you provide the wording you would like for the bubble to include?

**Comment by tlcurran** [comment]
SOMETHING LIKE THIS?  Not 100% on wording.  Suggestions welcomed. 

Leave a message to the Angel volunteers who are looking to adopt a service member during their deployment.  It can be as short as "Thank you for your support." or as lengthy as "Hello, I'm currently deployed to the Middle East.  I love reading and doing puzzles.  My favorite snacks are chocolate chip cookies.  Thank you for adopting me through my deployment."

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! The "bubble" text has been added to the "Message to Adopting Angel" field on the Deployed Adoption Program. We just used the text that was supplied above. If you'd like to make changes, we can most definitely do that. Thanks!
