### ISSUE TITLE
Client - Deployed Registration - Submitted by Phone

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#39]
Can this be phone format 910-496-5441 or (910) 496-5441 or 011-49-111-1111?

[Client - Deployment Registration - Who signs you up info.pdf](https://github.com/pltarr/sa-database-testing/files/2804344/Client.-.Deployment.Registration.-.Who.signs.you.up.info.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy, this has been completed. The system will auto format the telephone like such: (123) 123-1234. Thanks!
