### ISSUE TITLE
Registering - Team Angel Ladies of Liberty

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#4]
Signing up as a Team Angel and Ladies of Liberty.  “I confirm that I understand I must send 1 card or letter to each troop” should be removed.  “I confirm that I understand I am not to send a care package” should be I confirm that I understand I am to send a care package. 

![image](https://user-images.githubusercontent.com/46329541/50615814-3ef1c180-0ea3-11e9-9f31-a5e4c3b7d63e.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The "consent" questions on the Ladies of Liberty program have been updated. Please let me know if anything else here needs to be adjusted. Thanks!
