### ISSUE TITLE
Client - Deployed Registration - Submitted by Email Address

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#40]
Submitted by email address should require correct email format and be required.

[Client - Deployed Registation - Submitted by Email Address.pdf](https://github.com/pltarr/sa-database-testing/files/2804368/Client.-.Deployed.Registation.-.Submitted.by.Email.Address.pdf)

**Comment by tlcurran** [comment]
Ok, when hit submit, it did tell me to go back and correct this.  Could this message show when you enter it and not after trying to move to next screen?

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! We modified the formatting of the "Submitted By Phone Number" and "Submitted By Email Address" fields when selecting the Spouse or Other options. Please let me know if you have any questions. Thanks!
