### ISSUE TITLE
Client - Deployed Registration - SOFT Registration page 2

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#41]
The SOF box should be checked on page two, since I said I was SOF on first page.

[Client - Deployed Registration - SOF Box.pdf](https://github.com/pltarr/sa-database-testing/files/2804383/Client.-.Deployed.Registration.-.SOF.Box.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! This has been completed as well. Please let me know if you have any questions. Thanks!
