### ISSUE TITLE
Team Angel - Registration - Date of Birth under 18

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#42]
To volunteer you must be 18 years or older, but registered as a minor.  This should be a required field.

[Team Angel - Registration - Date of Birth.pdf](https://github.com/pltarr/sa-database-testing/files/2804525/Team.Angel.-.Registration.-.Date.of.Birth.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! You got it!

**Comment by tlcurran** [comment]
Thank you!

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! We have added validation on the Angel/Team Angel Signup so that only individuals who are 18 or older can signup. Please let me know if you have any questions. Thanks!

**Comment by tlcurran** [comment]
I tried this, this morning and it let me register under 18.  Well, I take that back, as after checking the volunteer agreement book it went to a page that said "Forbidden Error 403".
[Angel - Registration - Angel of Angel.pdf](https://github.com/pltarr/sa-database-testing/files/2872898/Angel.-.Registration.-.Angel.of.Angel.pdf)

**Comment by putn1nr** [comment]
@tlcurran Good morning Tracy! I entered 2/19/2001 for an Angels birthday (making them 1 day shy of 18 years old). Upon submitting the form, at the top of the registration form, I get the error:

Date of Birth: Sorry! You are not 18 years old. Must be 18 years old to register for Soldiers' Angels.

![image](https://user-images.githubusercontent.com/46578151/52960018-ce750600-3365-11e9-87f9-d62cca61aa6d.png)

Would you mind trying/testing once more?

Thanks,
Nicole
