### ISSUE TITLE
Team Angel - Registration - Text messages

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#43]
If saying "yes" to text messages, need to confirm phone number previously inputted is where they want text or need to enter number they want text to be received.

[Team Angel - Registration - Texting.pdf](https://github.com/pltarr/sa-database-testing/files/2804547/Team.Angel.-.Registration.-.Texting.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy, you got it!

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! Hope you are doing well - just wanted to let you know that this has been completed. Let me know if you have any questions. Thanks!
