### ISSUE TITLE
Team Angel - Registration - Other

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#44]
Does "Other" need a place to tell us where?

[Team Angel - Registration - Other.pdf](https://github.com/pltarr/sa-database-testing/files/2804556/Team.Angel.-.Registration.-.Other.pdf)

**Comment by putn1nr** [comment]
@sa-sturner / @tlcurran Hi Susie/Tracy! We are now displaying an additional field when the "Other" option is selected on the "How did you hear about Soldiers' Angels" field. Please review and let me know if you have any questions. Thanks!
