### ISSUE TITLE
Team Angel - Registration - Volunteer Handbook

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#45]
Where will the Volunteer Agreement be?

[Team Angel - Registration - Volunteer Agreement.pdf](https://github.com/pltarr/sa-database-testing/files/2804570/Team.Angel.-.Registration.-.Volunteer.Agreement.pdf)

**Comment by sa-sturner** [comment]
Duplicate, is already on Nicoles radar
