### ISSUE TITLE
Team Angel - Registration - LWT Assignments

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#46]
Confused by the question.  Are we having them be auto assigned daily or when they choose to get a service member or will they be allowed to look at them and choose?  They are normally auto assigned when request a name.

[Team Angel - Registration - LWT opp assignment.pdf](https://github.com/pltarr/sa-database-testing/files/2804593/Team.Angel.-.Registration.-.LWT.opp.assignment.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! Good question -- right now, the system will not auto assign Letter Writing opportunities. However, the Team Angel will have the ability to go to the Team Angel Portal and search and find Letter Writing opportunities that they would like to fulfill. 

This functionality has been backlogged (the auto-assignment of Letter Writing opportunities) and will be worked in accordingly. Thanks!
