### ISSUE TITLE
Team Angel - Registration - I confirm not required to send package

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#47]
The statement "I confirm that I understand that I am not required to send care packages" seems wrong.  LWT Angels are asked to not send care packages.

[Team Angel - Registration - I confirm 1.pdf](https://github.com/pltarr/sa-database-testing/files/2804619/Team.Angel.-.Registration.-.I.confirm.1.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! The reason we have this consent question under the Letter Writing Program is because it was there on the old system. Doesn't mean it has to be there in the new system. Would you like us to remove this consent question for the Letter Writing Program?

Please advise. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole
Yes please remove this consent. This was in the original specs that was not needed.  

Susie

**Comment by putn1nr** [comment]
@sa-sturner / @tlcurran Hi Susie & Tracy. The consent: "I confirm that I understand that I am not required to send care packages" has been removed from the Letter Writing Program when signing up as a Team Angel. Please let me know if you have any questions. Thanks!
