### ISSUE TITLE
Team Angel - Registration - USPS regulation

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#48]
We need another check off box on all team pages that states that angels will follow all USPS and MPS regulations when sending to service members.

[Team Angel - Registration - USPS.pdf](https://github.com/pltarr/sa-database-testing/files/2804630/Team.Angel.-.Registration.-.USPS.pdf)

**Comment by putn1nr** [comment]
@tlcurran Hi Tracy! On Step 1, we only have 1 check box selection and that is for the Angels/Team Angels to confirm they've read the Angel Agreement.

And then on the Ladies of Liberty and Letter Writing Programs (if selected during Step 2), we show additional check box selections. However, we only show these check box selections for these 2 Programs.

@sa-sturner Susie, should we have additonal check box selections / consent questions for all Programs (such as Adopt-A-Family, Baby Brigade, etc.)? 

Please advise. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr and @tlcurran 

Hi Nicole, 
For now we will add this to the Volunteer Agreement and in revisit during phase 2 requests.

**Comment by putn1nr** [comment]
@sa-sturner Thanks, Susie! This has been documented as "Phase 2".

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, I'm sorry I meant to close this.  Yes thank you
