### ISSUE TITLE
Admin:  Angels Master Search

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#49]
Would it be possible to include date registered?  
![image](https://user-images.githubusercontent.com/46329541/51941984-26f25c80-23d3-11e9-831c-2a1c5947d588.png)

On the Advanced Search filters can we include the date of birth: 
![image](https://user-images.githubusercontent.com/46329541/51942091-733d9c80-23d3-11e9-87c5-4dcbad5dc679.png)

On all searches related to dates is it possible to have these included:  
![image](https://user-images.githubusercontent.com/46329541/51943108-eba55d00-23d5-11e9-9c5d-bcc9ea5d967d.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Absolutely -- this has been scoped and worked into the development queue. Question: do  you want these enhancements added to the Service Member Search + List View as well? Or just Angels at this time? Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, both would be great.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We added the following "refine" filter options to the Angel Search:

- Added in "Date of Birth"
- Can refine all "Date" filters ("Approval Date" , "Date Registered" , and "Date of Birth") by: =. >, >=, <, <=, Yesterday, Today, Last Wek, Last Month, Last Quarter, Last Year

This functionality still needs to be added for the Service Member Search.

Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We also got the "refine" filters added to the Service Member Search. Please review and let me know if you have any questions. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
I would like to open this one back up to include everything that is listed in the screenshot.  To be able to look into future dates is used as well.
