### ISSUE TITLE
Registering - Team Angel donation 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#5]
Signing up as a Team Angel in the donation section, there is not a place for the quarterly option.  

![image](https://user-images.githubusercontent.com/46329541/50615842-5af56300-0ea3-11e9-86d4-1bfc7bbcd7a3.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We added in the "Quarter" option on the Team Angel Donation page (Step 4 of the Signup). We also added in an "Other Amount" column (which promotes additional donations/the option to give more). You will notice that there is some built in logic here as well -- for example: if a user tries to enter $1.00 in the Annual Donation > Other Amount column, we automatically overwrite it to the minimum Annual Donation amount (which is $12.00). This prevents anyone from trying to get out of making the minimum Donation.

Please review and let me know if you have any questions or additional feedback. Thanks!
