### ISSUE TITLE
Angel/Client - Female/Male

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#50]
Is it possible to have it when you hit "F" or "M", that it checks the box?  Right now, you get the drop down and have to click on the correct gender.

**Comment by sa-sturner** [comment]
@putn1nr If this could be done not only with the male/female portion but all drop down? Like qualifying persons status, etc.

**Comment by putn1nr** [comment]
@tlcurran / @sa-sturner Hi ladies. We will get this addressed on all dropdowns throughout the system (Angel/Team Angel Signup and Portals, Service Member Signup and Portal, and Soldiers' Angels Admin). Thanks!

**Comment by putn1nr** [comment]
@tlcurran / @sa-sturner Hi Tracy / Susie! All of the dropdowns have been addressed throughout the system. Please review and let me know if you have any questions. Thanks!
