### ISSUE TITLE
Angels - Ladies of Liberty and Letter Writing Step Three

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#51]
The first five questions under step three for Ladies of Liberty and Letter Writing team do not need to be there.  We do want them to be able to choose branch during a pull of a name, but we do not want to have an Angel be able to designate dates, times, branches, etc during registration

[Angels Registration questions.pdf](https://github.com/pltarr/sa-database-testing/files/2851057/Angels.Registration.questions.pdf)

**Comment by sa-sturner** [comment]
Disregard
