### ISSUE TITLE
Client - Registration picture

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#52]
We do not need the clients to upload pictures. 

![image](https://user-images.githubusercontent.com/46329541/52578358-5183e280-2de1-11e9-800f-a573a2a8e8a4.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We will have this functionality removed on the Service Member Signup and in the Service Member Portal (when they login). Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank you Nicole

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We removed the Service Member "profile" image from all applicable sections (Service Member Portal, Signup, Search, etc.). Thanks!
