### ISSUE TITLE
Angel & Client - new registrations 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#53]
Can we state somewhere that the email address is the user id?  We are able to do the password but it could cause confusion about the user id.  

![image](https://user-images.githubusercontent.com/46329541/52579812-39619280-2de4-11e9-96e2-69997fc669e0.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! I envision a "note" about email being the system username being in 1 of 2 spots:

Either directly below the "Email Address" field:

![image](https://user-images.githubusercontent.com/46578151/52676110-fba15e80-2ef6-11e9-9cdc-15057c93f3c1.png)

Or, above the "Password" and "Confirm Password" fields:

![image](https://user-images.githubusercontent.com/46578151/52676125-06f48a00-2ef7-11e9-969b-53b53d9ba8e1.png)

Do you prefer either placement? Or did you have another idea? Please just let me know. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

I prefer it to be:  above the "Password" and "Confirm Password" fields:

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Thanks for your input - we will get the text added above the "password" and "confirm password" fields. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

Great, thank you

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The note/text has been added above the "Password" fields on both the Angel/Team Angel Signup and the Service Member Signup. Please let me know if you have any questions. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
Thank you
