### ISSUE TITLE
Client - Registration Special Operation Forces

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#54]
Would it be possible to include Message to Angel in the Special Operation Forces questions in step 3 of registering?  

![image](https://user-images.githubusercontent.com/46329541/52592165-e9de8f00-2e02-11e9-9525-971a9a0d349f.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! You got it. From your screenshot, I gather that you'd also like the message "bubble" that would read -- "Please include a message to an Adopting Angel. This will only be seen by Special Operations Forces." 

Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

Hi Nicole, 

How about this for the bubble. 

You can leave a message here for your adopting angel(s) regarding items you could use, information/conditions at your location or just a thank you for their support of you and/or your team.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. You got it, thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank you Nicole

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. The "Message to Adopting Angel" question has been added to the Special Ops questions (on the Service Member Signup > Step 3). Also added the bubble/help text. Let me know if you have any questions. Thanks!
