### ISSUE TITLE
Admin:  History and Reporting

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#55]
When will we be able to see history and reporting in the Admin portion of the system?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Both of the items -- History and Reporting (specifically the Logbook Report) are being scope and worked into the development queue. How about we set a meeting for Friday or Monday to review the tasks (here in GitHub) as well as other items and begin setting priority. Let me know what you think!

**Comment by sa-sturner** [comment]
@putn1nr 

Hi Nicole, are you available Monday at 2:00 PM or 3:00 PM Central?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! I am available on Monday, at 2:00PM Central/3:00PM Eastern. Let me know if that still works for you and I can send out a meeting request. Thanks!

**Comment by sa-sturner** [comment]
That is perfect can you please include Louie, lguzman@soldiersangels.org

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
Do we have a scope of history yet?

**Comment by sa-sturner** [comment]
@putn1nr 
Do you need a list of who will need access to history and reports?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Yes, please provide me with what user roles should have acceess to the Angel/Team Angel History, Service Member History and Logbook Report (and other reports in the future). Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
I am getting final input on this and will get you the list as soon as I can.  

Susie
