### ISSUE TITLE
Client:  registering as women of valor

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#56]
While answering the women of valor questions it asks if you employed outside the home, I checked No but the "If employed, what do you do?" was a mandatory field.  

![image](https://user-images.githubusercontent.com/46329541/52655896-7b590a00-2eb2-11e9-94b8-6c8e6753fb00.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will remove the restriction/required validation on this field. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

Thank You

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The restriction/required validation on the "If employed, what do you do?" was removed. Thanks!
