### ISSUE TITLE
Client: registering women of valor- documents

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#57]
After I registered under women of valor and logged back into my profile I was shown a picture that was actually what I uploaded as my proof of wound/illness/injury.  But it doesn't say that on the profile page and I am not able to see the other two documents.  

![image](https://user-images.githubusercontent.com/46329541/52656229-210c7900-2eb3-11e9-9de1-1313b39cbd12.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The image being appended as the Service Member's Profile image will most definitely be addressed. 

Regarding not being able to find the files when logged into the Service Member Portal, upon "approving" your Service Member (i.e. the "SA Status") in the Service Memebr Portal a new tab will appear = Program Settings. Once on the Program Settings tab, if you click on Women of Valor Program text, you will see all of the responses to the questions during the Signup process as well as the files that were attached. If you'd like to walk through this together, just let me know.

Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

You are referring to the Admin login, correct?  

What I am referring to is logging back in as the client.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. No, actually, I am referring to the Service Member/Client Portal. If you login and the "SA Status" = Approved, there is a tab titled = Program Settings.

Clicking on "Program Settings" will then show all of the "Registered Programs" (i.e. Programs that were selected during the Signup) and "Additional Programs" (i.e. other Programs that the Service Member is eligible for based on their status and other questions).

Then, clicking on "Women of Valor", you will see all of the Women of Valor questions in addition to the files that were uploaded during the initial Signup.

![image](https://user-images.githubusercontent.com/46578151/52746497-a4ab9000-2faf-11e9-8532-60aec7cc11c3.png)

![image](https://user-images.githubusercontent.com/46578151/52746505-a9704400-2faf-11e9-9754-d10f7770dbff.png)

I hope this makes more sense! If not, we can walk through this during our next call. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
I think I understand it now, thanks.  :)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. The issue where the Service Member's profile image was displaying an image uploaded for the Proof of Wound/Illness/Injury has been addressed. Thanks!
