### ISSUE TITLE
Admin: Cards Plus Outstanding

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#58]
Can we add Post Date to the outstanding screen for cards plus. 

![image](https://user-images.githubusercontent.com/46329541/52670147-1662db80-2ed5-11e9-8df5-f4b16842cba5.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! "Post Date" has already been added to the Cards Plus > Outstanding List View. Please let me know if you have any questions. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank You
