### ISSUE TITLE
Angel & Client:  profile - submit a card request

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#59]
Submitting a card request we would like to make it a little simpler. 

![image](https://user-images.githubusercontent.com/46329541/52812745-741e3180-3055-11e9-8326-4d877c3678e2.png)

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, on this request I did submit it because in the spreadsheet that we submitted regarding our program rules we had it listed as the request be Service Member, Service Member's Family, Angel and Veteran.  I am not sure when it changed to what is in there.  BUT, if this is considered a change that we will be charged for I would like to hold off on this until phase 2.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This one is done too. Thanks!
