### ISSUE TITLE
Client - Valor IT log into profile 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#6]
When signing back in the profile does not tell me if I am approved/disapproved or what program I have registered for.  Nor does it allow me to register for Women of Valor or Adopt-A-Family.  

![image](https://user-images.githubusercontent.com/46329541/50615931-ac9ded80-0ea3-11e9-82d7-9cac53a3049f.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Your Susie Test account is still "Pending" therefore you cannot currently see what Programs that you have enrolled in during the Service Member Signup and/or enroll in additional Programs.

Once you approve the Susie Test account in the SA Admin, you can log back into your Susie Test account and you will see a new tab titled = "Program Settings". You should then see "Registered Programs" (these would be the Programs that you enrolled in during the Signup) and then see "Additional Programs" (these would be the Programs you are eligible for but did not enroll in during the Signup).

If you click on the name of the Program in either section -- "Registered Programs" or "Additional Programs" you will see the Program  specific questions.

Let me know if you have any other questions. Would be happy to walk you through this if you'd like. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr - so if I don't complete the profile I can not go in and upload documents or do anything until an admin changes the setting to something other than pending?  Does it have to be approved or can it be any setting?
