### ISSUE TITLE
Admin: DAT Group

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#62]
Trying to assigned One Angel to DAT Group it does not allow me to do anything in the team settings. The drop down does not drop down. 

![image](https://user-images.githubusercontent.com/46329541/52964620-f6fa0180-335f-11e9-8fad-47afa36a91d0.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Just wanted to let you know that this has been addressed. Once the Program Status is changed to = Active, you will have the ability to associate the Team Angel to a Group. Let me know if you have any questions. Thanks!
