### ISSUE TITLE
Admin: Approving Angel44

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#63]
When trying to approve Angel44 it would not save, and then I noticed that the Angel was not old enough to be approved.  But it was very difficult to see the error.  Any suggestions
![image](https://user-images.githubusercontent.com/46329541/52967993-25c8a580-3369-11e9-8478-658d43d4226f.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We need to trim the message that we display to SA Admin's. That is the same message we show on the Angel Signup (which makes sense) but it doesn't make as much sense in the SA Admin. We will get this addressed. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thanks Nicole

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This has been completed on the SA Admin. Now, when on the Angel Detail and the birthday gets changed to a date where the user is under 18, you will see the message: "Must be 18 years old."
