### ISSUE TITLE
Admin: Angel Master Search

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#64]
When using the filters and filtering for Ladies of Liberty there are no matches 

![image](https://user-images.githubusercontent.com/46329541/52968308-08480b80-336a-11e9-9b7a-911de6af2028.png)

But then I remove the filter for Ladies of Liberty, I can see at least two 

![image](https://user-images.githubusercontent.com/46329541/52968344-201f8f80-336a-11e9-93ab-9ecd592f5558.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Thanks for bringing this to my attention -- this will be addressed. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This was completed. You can search by "Program" and now see the appropriate results. Let me know if you have any questions. Thanks!
