### ISSUE TITLE
Angel Log in: Master Setting error message

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#65]
Logging in as an Angel, Angel24 I have a tab for Master Setting but when I click on it I get an error message. 

![image](https://user-images.githubusercontent.com/46329541/52970351-c1a9df80-3370-11e9-9075-eadf155d2971.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. I think this is because we are currently working on User Management/Permissions and we are still working through the development and testing. This will be addressed as soon as possible. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

Perfect, I thought maybe that was it but wanted to double check.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. This has been completed. Thanks!

**Comment by sa-sturner** [comment]
Awesome, Thank you 

@putn1nr
