### ISSUE TITLE
Admin - Client - Service Member Details 

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#68]
Where is the "Message to Angel".  It needs to be reviewed during approval.

**Comment by sa-sturner** [comment]
@tlcurran 
Hi Tracy, 
The message to Angel should be in the Team Settings tab under Deployed Adoptions.

**Comment by tlcurran** [comment]
Gotcha…think I figured that out last week but never updated.  SORRY!

Tracy Curran
Deployed Support Teams Program Manager
Soldiers' Angels
2700 NE Loop 410, Suite 310
San Antonio, TX  78217
Office: 210-629-0020
Cell: 210-510-1920
Fax: 210-629-0024
tcurran@soldiersangels.org<mailto:tcurran@soldiersangels.org>
www.soldiersangels.org<http://www.soldiersangels.org/>

May No Soldier Go Unloved

**Comment by sa-sturner** [comment]
@tlcurran 
Can we close?

**Comment by tlcurran** [comment]
Yes ☺

Tracy Curran
Deployed Support Teams Program Manager
Soldiers' Angels
2700 NE Loop 410, Suite 310
San Antonio, TX  78217
Office: 210-629-0020
Cell: 210-510-1920
Fax: 210-629-0024
tcurran@soldiersangels.org<mailto:tcurran@soldiersangels.org>
www.soldiersangels.org<http://www.soldiersangels.org/>

May No Soldier Go Unloved
