### ISSUE TITLE
Admin - reviewing Valor IT profile

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#7]
When logged in as an admin, the account is pending looking at the documents will we be able to click on the document and view it on another page?  Does the document have to be PDF? 

![image](https://user-images.githubusercontent.com/46329541/50615976-deaf4f80-0ea3-11e9-89b5-751e92957308.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! When viewing any of the files that were uploaded during the Service Member Signup process, by clicking on the file name, depending on the file type, the file will open in a new window/tab. PDF's and image files (such as .png's or .jpg's) will open in a new window/tab. Word documents will download to your local computer. (You can see an example by going to my test account -- GI Joe. Navigate to Team Settings > Adopt-A-Family and click on the "Test.pdf" link.
