### ISSUE TITLE
Angels - opportunities list

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#70]
Angels should not be able to change the opportunity status, this should follow the rules for each program.  

![image](https://user-images.githubusercontent.com/46329541/53190143-2a3dca00-35c6-11e9-91c6-8354238725cf.png)

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 

This is different than the original specs that we provided.  It is a change that your team did and it is not a change that will work for us.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We did make some adjustments here (removed the "Close Opportunity" option for all of the one time Opportunities -- such as Angel Bakers and Letter Writing) as well as added in the "Log Additional Activity" form.

Could we sync up maybe later this week or early next week to review? I'd love to get your feedback to see how we can revise the Opportunities so that it is exactly as you had hoped. 

Let me know when would work for you and we can review. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
I can get with you tomorrow if you are available.  

Susie

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Would tomorrow at 1:00PM EST work for you? Please let me know, thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
That will work perfectly. 

If we have time can I add another process that I would like to talk with you about on the service members?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Absolutely - let's discuss Service Member process as well. Looking forward to it!

**Comment by putn1nr** [comment]
@sa-sturner Good morning Susie! I have scoped out the rules for how an opportunity comes off the Team Angel "Current Opportunity" list. We have one and dones (1 time activity; such as Letter Writing) and recurring opportunities (frequent activity; such as Deployed Adoption). Would you mind looking this over to double check that the rules/logic is accurate? I referenced the Final Program Rules spreadsheet. 

If anything needs to be adjusted, please let me know. Thanks!

[Opportunity Status Logic-3-20-19.docx](https://github.com/pltarr/sa-database-testing/files/2992455/Opportunity.Status.Logic-3-20-19.docx)

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 

I did take a look at this and we only have 2 programs that are ongoing support, Deployed Adoptions and Special Forces.  With these 2 teams, Angels provide support until their mail stop date.  

All other teams are 1 and done.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Thank you for the clarification. We will have the "My Opportunities" section updated in the Team Angel Portal. I will be back in touch again when this is ready for testing. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We have updated the Team Angel Portal > My Opportunities. For the following Programs, only 1 Activity record can be saved. The Opportunity then moves to "Completed":

**One and done Opportunities:**
- Adopt-A-Family
- Angel Bakers
- Baby Brigade
- Cards Plus
- Chaplain Support
- Ladies of Liberty
- Letter Writing
- Living Legends
- Sewing and Crafting

For the following Programs, a Team Angel can log multiple/numerous Activity records. The system will automatically move the Opportunity to "Completed" 30 days prior to the Service Member's "Mail Stop Date" (or an Admin can manually modify the assignment/Opportunity anytime via the Admin Portal):

- Deployed Adoption
- Special Ops

Please review and let me know if you have any additional feedback/observations. Thanks!
