### ISSUE TITLE
Admin - Programs activity tab

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#72]
It would be helpful to be able to search by Service member name as well as angel name.  For all programs under the Program - Activities tab. 

![image](https://user-images.githubusercontent.com/46329541/53195224-77c03400-35d2-11e9-87a3-a7ac3e1d4ed4.png)

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
Can we get a quote on this?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Let me talk w/ the team about this one next week. I will get you a scope of work and an estimate of time as well. Be back in touch soon on this one. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr Thanks Nicole

**Comment by sa-sturner** [comment]
Closed:  submitted a support ticket via google.
