### ISSUE TITLE
Client: Registration Wounded, Ill, Injured - Zip Code

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#73]
Signed up as wounded, ill, injured and the system did not flag when I didn't enter in a 5 digit zip code, I only entered in 3 numbers. 
![image](https://user-images.githubusercontent.com/46329541/53381872-74f57400-392f-11e9-8e53-c10fdbeb6dbb.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! All Zip Code fields throughout the application are now being validated and require 5 digits to be entered. Please review and let me know if you have any questions. Thanks!
