### ISSUE TITLE
Client - Registration as Wounded, Ill, Injured - Valor IT Case Manager

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#74]
When registering for Valor It and completing the additional questions regarding the case worker I did not enter in an email address or complete phone number.  
![image](https://user-images.githubusercontent.com/46329541/53382080-39a77500-3930-11e9-9302-dec516f3ea96.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. We will modify the validation on the Valor IT -- Case Worker's Email Address and Case Worker's Phone Number fields. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank You

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. When registered for the Valor IT Program as a Service Member, the Case Worker Email Address and Case Worker Phone Number fields have been updated. Please review and let me know if you have any questions. Thanks!
