### ISSUE TITLE
Client - Women of Valor signed in

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#78]
When logging in as an approved Women of Valor client, I went into program settings and deleted a document.  When I deleted that one document it deleted all of the women of valor questions.  

Clients should not be able to delete a document that has already been uploaded.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This one is completed as well. When logging into the Service Member Portal, a Service Member cannot delete files that have been previously uploaded (either via the Service Member Signup or in the Service Member Portal). Please review and let me know if you have any issues. Thanks!
