### ISSUE TITLE
Client - Approval - Team Status - Chaplain

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#79]
Service member choose Chaplain on Service member details and it did not carry over to Team Details.

![client - approval 2](https://user-images.githubusercontent.com/46571815/53437790-66a96580-39cc-11e9-91ea-b147b9cbfea1.jpg)
![client - approval 3](https://user-images.githubusercontent.com/46571815/53437792-67da9280-39cc-11e9-943e-1f6a870d62d0.jpg)

**Comment by putn1nr** [comment]
@sa-sturner / @tlcurran Hi Susie / Tracy. This item has been addressed. Now, when logged in as an Admin, and updating a Service Member -- "Are you are Chaplain or Chaplain's Assistant" to = Yes, on the Team Settings tab, the Chaplain Support Program is checked, a "Date Requested" is recorded, and the Status is marked = Pending - Other. Could you please review? Thanks!
