### ISSUE TITLE
Client - Registration for deployed service member

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#8]
Using email address sturner1@soldiersangels.org.  When registering as a deployed service member I left off the phone number.  I was not allowed to proceed to the next step since it was missing but it was not very clear that was the problem.  After clicking next step was brought to step 2 asking what programs are you interested in being a part of?  All male deployed service members are automatically a part of Deployed Adoptions and Letter Writing Team, these teams are not an opt-in team.  Also during step 1 I choose that I was a Chaplain Assitant, I should not be asked this in step 2.  
![image](https://user-images.githubusercontent.com/46329541/50618814-6603bf80-0eb2-11e9-8f3b-499d86d5cf0d.png)

**Comment by sa-sturner** [comment]
using email address:  sturner1@soldiersangels.org

**Comment by sa-sturner** [comment]
Using email address sturner2@soldiersangels.org signing up as a female moving the system allowed me to put a mail stop date in the past. When in step 2 asked what programs interested in being a part of.  All female deployed service members are automatically a part of Deployed Adoptions, Letter Writing Team, and Ladies of Liberty.  I also opted into Angel Bakers.  Step 3 did allow me to answer if I had allergies for Angel Bakers but it asked me for message to angel for both ladies of liberty and deployed adoptions, this should be one message during step 1.

**Comment by sa-sturner** [comment]
While this is automatically added or checked off for the appropriate teams we do not want a new client that is registering to be able to opt OUT of deployed adoptions, letter writing, ladies of liberty (if female). 

![image](https://user-images.githubusercontent.com/46329541/51134915-0c768b80-17f6-11e9-8897-9dea3ffe99b9.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will add the additional logic so that a "Deployed" Service Member cannot un-select the auto-selected Programs (i.e. Deployed Adoption, Letter Writing, and Ladies of Liberty if Gender = Female). Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Couple updates here:

- Now when registering as a "Deployed" Service Member, when getting to the Program selection (Step 2), the Service Member cannot opt-out of Deployed Adoption, Letter Writing or Ladies of Liberty (if Gender = Female).

- Service Members can no longer enter a "Mail Stop Date" that is in the past or a "Birthdate" this in the future.
