### ISSUE TITLE
Admin: Program settings vs service member

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#81]
![image](https://user-images.githubusercontent.com/46329541/53439220-d44e9500-39be-11e9-86db-36cb8b9574c4.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! The Program Statuses in the Program Management >Angels and Service Members tabs are now reflective of the correct status options. Please review and let me know if you have any questions. Thanks!
