### ISSUE TITLE
Client - Approval tabs saving issue

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#82]
Approvals are difficult.  I've tried:

1.  Approving under Soldiers' Details first, then clicking to Team Settings and changing status, hitting save on Team Settings and then on Soldiers' Details.  All statuses under TEam Settings change back to pending.
2.  Approving under Team Settings and saving, then go to Soldiers' Details and approving.  Team settings go back to pending and have to be reapproved and saved.
3.  Approved on Soldiers' Details and save and brings me out of the approval and have to go to another search to find service member and approve Team Details.

There needs to be a way to approve on first screen or second and have that info stay and go to other screen.  Having to go in and out of searches to do a complete approval will be difficult.

**Comment by sa-sturner** [comment]
@tlcurran 
Tracy, lets walk through this together, the only thing that would concern me is if there is a crossover with DST and FST in the event of AAF and BB.

**Comment by tlcurran** [comment]
I know we chatted about this, but while approving or trying to this morning, this issue is important to me. 
 We (I) need to be able to save under all tabs (Service Member Details and Team Settings) while doing approvals without being kicked out of the service member profile.  Also need the changes made under Team Settings (changing from Pending Other to Pending Address Update for example) to stay when I hit save and Service Member Details is still showing as Pending.  Currently, it goes back to Pending other.
