### ISSUE TITLE
Client - Approvals - Chaplain status

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#83]
1.  Approved Chaplain and saved.
2.  Had to find Chaplain again to look at teams under approved.
3.  Under Team Details, approved DST, AB, and LWT and saved.   The system changed CST to approved too.  Should have stayed at pending
![client - approval cst not pending status](https://user-images.githubusercontent.com/46571815/53443367-885d1980-39d9-11e9-9ed3-2e64499465d2.jpg)
.

**Comment by sa-sturner** [comment]
@tlcurran 

This is my fault, I thought you were going to change CST manually and that it was okay to update it with the others.
