### ISSUE TITLE
PRIORITY:  User Permissions - Team Leaders

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#85]
@putn1nr 
Hi Nicole, 
Part 1:  I might have made a mistake when providing the team leader status.  They will need access to the programs as this is where they can see the opportunities.  I did not state it in the first portion but do have it listed as to what they cannot change the program settings in the programs tab.  They should be able to view all Team Angels and Servicemembers but only be able to make changes to their designated teams.  BUT, they do need access to the Program settings, they just can't change the program settings tab information. 

From original Document:  DST Team Leader – access to Team Angels and Service Members, cannot archive or change SA Status for Team Angels or Clients, **can only change team status for their team**, **cannot change program settings**
FST Team Leader – access to Team Angels and Service Members, can only change team status for their team, cannot archive or change SA Status for Team Angels or Clients, **cannot change program settings**, change team status for clients

Part 2:  Also, when I set up a DST team leader and tried to log in as her, there are no Team Angels or Service Members listed.  Will new Team Angels and/or Service Members need to be added for them to be able to see them?

**Comment by sa-sturner** [comment]
Would it be possible to add a feature to VA Support – access to Angels and Team Angels, to include their assigned region?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Just wanted to let you know that I have seen all of the recent items documented here in GitHub and I am working to get these scoped. I see that the User Permissions are marked "Priority" -- so I will get these pushed to the top of the development queue. I will be in touch with any questions. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, thank you.  Please keep in mind that some of these that say pending SA review has not been approved yet by Amy to be done.  Anything that is a change or new I have to get her approval first, anything that is a bug can be done.  I have not submitted those that say pending SA review for her review and approval yet.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Can you please provide me with the DST Leader account (username/password) that you created where you are not seeing the correct Angel/Service Member associations. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

Of course.  It is for Pat Fried, pfried@soldiersangels.org , here2help

**Comment by sa-sturner** [comment]
@putn1nr 
The leader accounts will have to be able to view all team angels and their information.  Is this not possible?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Yes, of course we call allow Team Leaders to view all Team Angels and their information. It looks like we may have to make a couple adjustments so that they can see ALL Team Angels and ALL Service Members and not just those in their selected Programs.

However, the Team Leader would only be able to edit Program Settings for the Programs they are associated to, correct?

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
That is correct, thank you so much.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. You got it - we will make the appropriate adjustments to the Team Leaders (Deployed and Family Support). All other user roles can be checked. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Fantastic

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Please check Deployed Support and Family Support Team Leaders again. They have access to ALL Angels and Service Members. However, they can only modify Team Settings for their selected Programs. Can only update Program Settings for their selected Programs as well.

They CANNOT modify the SA Status for either Angels or Service Members.

Please let me know if you have any questions or see anything that needs to be addressed. Thanks!
