### ISSUE TITLE
Admin:  Program Manger permission

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#87]
@putn1nr 

Hi Nicole, 

On the program manager permissions, they do not have access to the Programs - Cards Plus - Pending Requests.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We will get this addressed. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! This has been completed. Thanks!
