### ISSUE TITLE
Angel:  Registration - BUG

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#88]
Registering as Angel100, vsarracino100@soldiersangels.org, allowed me to  enter an incorrect 4 digit zip.    Allowed street with no house number

Registering as Angel102, vsarracino102@soldiersangels.org, allowed for 3 digit zip.  Allowed for a different country  with CT as the state

Registering as Angel104, sarracino104@soldiersangels.org, Let me use a San Antonio address but chose the state as AE

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! A couple ways to handle this feature -- we can implement a 3rd party API (called SmartyStreets) that would allow address validation/pre population on all address fields throughout the system. Example: https://smartystreets.com/products/single-address. Or, we can add validation for zip code fields to ensure there are 5 digits. Let me know what you think. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 

Hi Nicole, 

I think the main concern is that it is allowing us to put 3 digits instead of 5 digits for a zip code.  We had several people test last Thursday and Friday that when they put in the correct zip code that they were receiving an error message that it was incorrect.  

I do not think we need the 3rd  Party API at this time.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! I noticed the message "Please enter a valid Zip Code" went entering a valid Zip Code on the Signup forms as well. We are addressing this to ensure there is validation on 5 digit Zip Codes but not to show the error/message when a VALID 5-digit Zip Code is entered. I will keep you posted on this one. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, that is great.  Thank you so much.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! We have addressed the validation on all of the Zip Code fields throughout the system (must enter 5 digits). Please review and let me know if you have any questions. Thanks!
