### ISSUE TITLE
Client - Deployed - Approval/Disapproval/Pending Save function

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#90]
When approving "Pending" under Service Member Details, is it possible to click save and not have it go back to the search grid?  It does this under Team Settings, but not Service Member Details.  

Issue is when I do something as simple as adding a note and want to save it before going to Team Settings, it takes me to the main grid. 

I know we discussed this the other day Susie, but didn't see anything in list.

**Comment by tlcurran** [comment]
Also need this page to stay on Service Member Details so that we can go to Team Settings without having to write down service member name and have to search to go back in and do the updates needed under Team Settings (if needed...but still need to be able to confirm).

**Comment by sa-sturner** [comment]
@tlcurran 
Isn't this a part of issue #82

**Comment by tlcurran** [comment]
Yes, it is ☺  Sorry!

Tracy Curran
Deployed Support Teams Program Manager
Soldiers' Angels
2700 NE Loop 410, Suite 310
San Antonio, TX  78217
Office: 210-629-0020
Cell: 210-510-1920
Fax: 210-629-0024
tcurran@soldiersangels.org<mailto:tcurran@soldiersangels.org>
www.soldiersangels.org<http://www.soldiersangels.org/>

May No Soldier Go Unloved

**Comment by tlcurran** [comment]
Part of 82.
