### ISSUE TITLE
Client - Deployed - Approved no opportunties approved

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#91]
Approved Service8 Member8 (changing from male to female during this process) and after saving Approved under Service Member details, no opportunites were change to Approved.  Is this so it can be done one by one now?  If so, need to go back to when hitting Save under Service Member Details, not being sent back out to the search page

**Comment by sa-sturner** [comment]
@tlcurran 
Did you update them manually under team settings?  when I looked at them there were approved for AB, DAT and LWT.  But LOL was disapproved.

**Comment by tlcurran** [comment]
Is there a delay in them updating?  I'll have to test again.
