### ISSUE TITLE
Client - Deployed - Male/Female change

### ISSUE THREAD

**Issue by tlcurran** [pltarr/sa-database-testing#92]
During approval, if change from female to male, can the opportunity for LOL disapprove or delete?

**Comment by sa-sturner** [comment]
@tlcurran 
Is this something you have already tried?  changing from female to male during approval?

**Comment by tlcurran** [comment]
Only this one time, I believe.

Tracy Curran
Deployed Support Teams Program Manager
Soldiers' Angels
2700 NE Loop 410, Suite 310
San Antonio, TX  78217
Office: 210-629-0020
Cell: 210-510-1920
Fax: 210-629-0024
tcurran@soldiersangels.org<mailto:tcurran@soldiersangels.org>
www.soldiersangels.org<http://www.soldiersangels.org/>

May No Soldier Go Unloved
