### ISSUE TITLE
Registration - Client Adopt-A-Family # of children message

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#93]
When trying to register for Adopt-A-Family and placing a number in the number of children field as given an error message regarding zip code.  

![image](https://user-images.githubusercontent.com/46329541/54123789-40b99300-43c6-11e9-8c4f-345d1541d101.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! While I was testing last Friday, I noticed this as well. This has already been documented and sent to the team. Thanks!

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Just wanted to let you know that this item has been addressed/completed. Let me know if you have any questions. Thanks!
