### ISSUE TITLE
Admin: client approvals - might be better to chat about this 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#94]
@putn1nr 
Hi Nicole, 
The following issues are somewhat similar and probably will work themselves out.  If possible we would like to talk about this.  

Issues:  67, 77, 80, 82 and 83

Proposed thoughts:  When working in the service member details and team settings for a client and making any change on these screens, we should 1.  Be able to go between the two screens and anything changed remaining changed until we hit save and 2.  we need to be able to save in either the service members details tab or the team settings tab and remain in the service members profile and not be removed from it.

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! Let's definitely add this to the discussion for tomorrow. Looking forward to catching up, thanks!
