### ISSUE TITLE
Admin : Special Forces 

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#96]
When in the Special Forces tab there is a new tab under Programs "Pending Requests".  What is this?

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. The "Pending Requests" tab is a list of all of the Service Members who have requested the Special Ops Program (either via the Signup form or through the Admin). This allows you as an SA Admin to "vet" the request prior to the Opportunity being posted out for Team Angels. 

If you'd like to review this together, please let me know. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, let me get with Tracy on this Monday.  She is out of the office today.
