### ISSUE TITLE
Admin: Program setting email notifications

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#97]
@putn1nr 
Hi Nicole, 
This was on the original screenshots but I haven't seen it anywhere.  Is this feature still in the database?  

![image](https://user-images.githubusercontent.com/46329541/55115199-86a27680-50a9-11e9-8dac-8d586b304cc8.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. Just wanted to let you know that I seen your note here and that I've added it to the master GitHub spreadsheet. Thanks!

**Comment by sa-sturner** [comment]
@putn1nr 
Thank you Nicole, is this feature no longer available?

**Comment by putn1nr** [comment]
@sa-sturner It's not that it isn't available - we just have not built this feature out yet. We would need to further define and scope this and get it into the development queue. I'd suggest we get through reporting and e-Commerce and then pick this one back up. Let me know if it needs to take a higher priority. Thanks.
