### ISSUE TITLE
Admin: create new opportunity

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#98]
@putn1nr 
Hi Nicole, 
When creating a new opportunity the original screenshots had a drop-down menu for the service member name but now it is a blank box.  Curious as to why the change. 

![image](https://user-images.githubusercontent.com/46329541/55115334-e0a33c00-50a9-11e9-85a7-6d0fa1ecac2d.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie! On the "Create a New Opportunity" modal popup, the "Service Member" field is a type-ahead dropdown. So for example, Program = Angel Bakers. If you start to type in Bill Booker or Johnny Cash, you will see that they are available to be selected. We only show Service Members who are approved for that specific Program in the type-ahead.

Should this be changed?

**Comment by sa-sturner** [comment]
@putn1nr Hi Nicole, okay we will test this again.  It was an open box that we were typing the name in.  We will revisit.
