### ISSUE TITLE
Team Angel: search opportunities

### ISSUE THREAD

**Issue by sa-sturner** [pltarr/sa-database-testing#99]
@putn1nr 
Hi Nicole, 
In the screenshots when searching for Chaplain Support opportunities it had a description of the items requested when scrolling through.  That feature is no longer available, where did it go. 

![image](https://user-images.githubusercontent.com/46329541/55115774-f107e680-50aa-11e9-8372-b193519a328a.png)

**Comment by putn1nr** [comment]
@sa-sturner Hi Susie. When doing a Chaplain Support search in the Team Angel Portal, we only show a little detail on each Service Member (such as: Name, Home State and Branch of Service). When the Team Angel "selects" a Service Member (by clicking the "Assign Service Member!" button), more detail is then displayed to the Team Angel:

- Mailing Address
- Appreciation Letter Detail/Care Package Detail/Etc.
- Number of Male Service Members
- Number of Female Service Members

Here is an example of a Team Angel "selecting" a Service Member:

![image](https://user-images.githubusercontent.com/46578151/55191075-9daf9a00-5177-11e9-9200-5b570c6a3935.png)

Should we be showing more to a Team Angel BEFORE they make a selection? Please just let me know.

Thanks,
Nicole

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, We may need to review this together.  We would like it to be like the wireframe, that before they select the opportunity they see the information about it.  For example, if it is the appreciation letter opportunity they would see the Appreciation details, if it is the care package opportunity they would see the care package items details BEFORE they select the opportunity.  Then if they select the opportunity for appreciation letters they would see: 

![image](https://user-images.githubusercontent.com/46329541/55248987-a30cf300-5210-11e9-8714-fd60725687dd.png)

BUT, this does not have to be done before we roll out as the importance of history, reporting and ecommerce are have to have.

**Comment by sa-sturner** [comment]
@putn1nr 
Hi Nicole, 
We would prefer it like the wire frame, that the angel be able to see before selecting if it is appreciation, care package, humanitarian or religious with the detail information.
